version: "3.2"
name: "sgbd-prep"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "6YECntP6GX7J$!"
      ACCEPT_EULA: "Y"
